# Session 2 HW

Calculating the distance between atoms in water

In [7]:
# import file using numpy
import os
import numpy
file = os.path.join('data','water.xyz')
coordata = numpy.genfromtxt(fname=file, dtype='unicode', skip_header=2)
print(coordata)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [9]:
# separate numbers and words
atoms=coordata[:,0]
print(atoms)
coords=coordata[:,1:]
print(coords)

['O' 'H1' 'H2']
[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [11]:
# convert numbers to float
coords=coords.astype(numpy.float)
print(coords)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [28]:
# calculate distances using distance formula 
# distance formula is sqrt((x2-x1)^2 + (y2-y1)^2 +(z2-z1)^2)
distance=numpy.sqrt(((coords[1,0]-coords[0,0])**2) + ((coords[1,1]-coords[0,1])**2) + ((coords[1,2]-coords[0,2])**2))
print(distance)
num_col=len(coords[0:])
print(num_col)

0.9690005374652793
3


In [51]:
# loop through every possible combination
# add labels
for i in range(0,num_col):
    for j in range (0,num_col):
        distance=numpy.sqrt(((coords[j,0]-coords[i,0])**2) + ((coords[j,1]-coords[i,1])**2) + ((coords[j,2]-coords[i,2])**2))
        print(F'{atoms[i]} to {atoms[j]}: {distance:.3f}')

O to O: 0.000
O to H1: 0.969
O to H2: 0.969
H1 to O: 0.969
H1 to H1: 0.000
H1 to H2: 1.527
H2 to O: 0.969
H2 to H1: 1.527
H2 to H2: 0.000


In [2]:
import os
import numpy
data_loc = os.path.join('data','water.xyz')
coordata = numpy.genfromtxt(fname=data_loc, dtype='unicode', skip_header=2)
atoms=coordata[:,0]
coords=coordata[:,1:]
coords=coords.astype(numpy.float)
num_col=len(coords[0:])
file=open('bond_lengths.txt','w+')
for i in range(0,num_col):
    for j in range (0,num_col):
        distance=numpy.sqrt((coords[j,0]-coords[i,0])**2 + (coords[j,1]-coords[i,1])**2 + (coords[j,2]-coords[i,2])**2)
        if distance<=1.5 and i>j:
            file.write(F'{atoms[i]} to {atoms[j]}: {distance:.3f} \n')
file.close()